# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test and Lint modules

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "releases/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_PLAYGROUND_URL: ${{ vars.NEXT_PUBLIC_PLAYGROUND_URL }}

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for doc changes
        id: changed-docs-files
        uses: tj-actions/changed-files@v42
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            packages/fuma-docs/**
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Yarn install
        run: yarn
      - name: Debug playground env (safe)
        run: |
          if [ -n "${NEXT_PUBLIC_PLAYGROUND_URL:-}" ]; then
            echo "NEXT_PUBLIC_PLAYGROUND_URL is set"
          else
            echo "NEXT_PUBLIC_PLAYGROUND_URL is NOT set"
          fi
      - name: Build all
        if: steps.changed-docs-files.outputs.any_changed == 'true'
        run: yarn build
      - name: Build modules only
        if: steps.changed-docs-files.outputs.any_changed == 'false'
        run: yarn build:modules
      - name: Lint
        run: yarn lint
      - name: Playwright install
        run: npx playwright install --with-deps chromium
      - name: Test
        run: yarn test
